#!/bin/bash

# 测试 Provider 和 Model 覆盖功能

echo "🧪 Testing Provider and Model Override"
echo "======================================="
echo ""

echo "📋 Available options:"
echo ""
echo "1️⃣  Default (Zhipu + glm-4-flash):"
echo "   ./target/release/llm-link --app codex-cli"
echo ""
echo "2️⃣  Override provider to OpenAI:"
echo "   ./target/release/llm-link --app codex-cli --provider openai"
echo ""
echo "3️⃣  Override provider and model:"
echo "   ./target/release/llm-link --app codex-cli --provider openai --model gpt-4"
echo ""
echo "4️⃣  Override only model (keep Zhipu):"
echo "   ./target/release/llm-link --app codex-cli --model glm-4"
echo ""
echo "5️⃣  Use Anthropic Claude:"
echo "   ./target/release/llm-link --app codex-cli --provider anthropic --model claude-3-5-sonnet-20241022"
echo ""
echo "6️⃣  Use Ollama:"
echo "   ./target/release/llm-link --app codex-cli --provider ollama --model llama2"
echo ""

echo "======================================="
echo ""
echo "🔍 Testing help message..."
echo ""

./target/release/llm-link --help | grep -A 3 "provider\|model"

echo ""
echo "======================================="
echo ""
echo "✅ Provider override feature is ready!"
echo ""
echo "📝 Examples:"
echo ""
echo "# Use OpenAI GPT-4 instead of Zhipu"
echo "OPENAI_API_KEY=xxx \\"
echo "LLM_LINK_API_KEY=xxx \\"
echo "./target/release/llm-link --app codex-cli --provider openai --model gpt-4"
echo ""
echo "# Use Anthropic Claude"
echo "ANTHROPIC_API_KEY=xxx \\"
echo "LLM_LINK_API_KEY=xxx \\"
echo "./target/release/llm-link --app codex-cli --provider anthropic"
echo ""
echo "# Just change the model (keep Zhipu)"
echo "ZHIPU_API_KEY=xxx \\"
echo "LLM_LINK_API_KEY=xxx \\"
echo "./target/release/llm-link --app codex-cli --model glm-4"
echo ""

