#!/bin/bash

# Provider 隔离测试脚本
# 验证 XML 转换只对 Zhipu provider 生效

echo "🧪 Testing Provider Isolation for XML Conversion"
echo "================================================"
echo ""

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo "📋 Test Scenarios:"
echo "--------------------------------"
echo ""
echo "1. ✅ Zhipu Provider + Standard Client"
echo "   → Should convert XML to JSON"
echo ""
echo "2. ✅ Zhipu Provider + ZhipuNative Client"
echo "   → Should preserve XML"
echo ""
echo "3. ✅ OpenAI Provider + Any Client"
echo "   → Should NOT attempt XML conversion"
echo ""
echo "4. ✅ Anthropic Provider + Any Client"
echo "   → Should NOT attempt XML conversion"
echo ""

echo "📝 Implementation Details:"
echo "--------------------------------"
echo ""
echo "The XML conversion logic now includes:"
echo ""
echo "1. Provider Check:"
echo "   if !is_zhipu {"
echo "     return; // Skip XML conversion"
echo "   }"
echo ""
echo "2. Configuration Check:"
echo "   if preserve_xml == true {"
echo "     return; // Skip XML conversion"
echo "   }"
echo ""
echo "3. XML Detection & Conversion:"
echo "   if xml::transform_xml_in_json_response(data) {"
echo "     // Convert XML to JSON"
echo "   }"
echo ""

echo "🔍 What to Look for in Logs:"
echo "--------------------------------"
echo ""
echo -e "${GREEN}For Zhipu Provider:${NC}"
echo "  • '🔍 Checking for XML in Zhipu response...'"
echo "  • '🔄 Successfully converted XML to JSON in response' (if XML found)"
echo "  • '✓ No XML found in response' (if no XML)"
echo ""
echo -e "${YELLOW}For Non-Zhipu Providers:${NC}"
echo "  • '⏭️  Skipping XML conversion: not a Zhipu provider'"
echo ""
echo -e "${YELLOW}For ZhipuNative Client:${NC}"
echo "  • '⏭️  Skipping XML conversion: preserve_xml is enabled'"
echo "  • '🔧 ZhipuNative adapter: preserving original XML format'"
echo ""

echo "🧪 Test Commands:"
echo "--------------------------------"
echo ""
echo "Test 1: Zhipu + Codex (should convert)"
echo -e "${YELLOW}RUST_LOG=debug ./target/release/llm-link --app codex-cli${NC}"
echo ""
echo "Test 2: Zhipu + ZhipuNative (should preserve)"
echo -e "${YELLOW}curl -H 'x-client: zhipu-native' http://localhost:8088/v1/chat/completions${NC}"
echo ""
echo "Test 3: OpenAI provider (should skip)"
echo "   → Configure with OpenAI backend, check logs for skip message"
echo ""

echo "================================================"
echo -e "${GREEN}✅ Provider isolation is implemented!${NC}"
echo ""
echo "Key Points:"
echo "  • XML conversion ONLY happens for Zhipu provider"
echo "  • Other providers (OpenAI, Anthropic, etc.) are NOT affected"
echo "  • Safe to use with any LLM provider"
echo ""

