# LLM Link Configuration - Codex CLI HTTPS-style Port
#
# This configuration runs on port 443 (HTTPS standard) for maximum compatibility
# Some tools expect OpenAI API on standard HTTPS port

# Server configuration - HTTPS standard port
server:
  host: "0.0.0.0"
  port: 443   # Standard HTTPS port (requires sudo on Unix systems)
  log_level: "info"

# LLM backend configuration
llm_backend:
  type: "Zhipu"
  base_url: "https://open.bigmodel.cn/api/paas/v4"
  api_key: "${ZHIPU_API_KEY}"
  model: "glm-4-flash"

# API endpoint configurations - Pure OpenAI API only
apis:
  # OpenAI-compatible API (PRIMARY and ONLY)
  openai:
    enabled: true
    path: "/v1"  # Standard OpenAI path - makes it http://localhost:443/v1/
    api_key_header: "Authorization"
    api_key: "${LLM_LINK_API_KEY}"

  # Ollama API (DISABLED)
  ollama:
    enabled: false
    path: "/ollama"

  # Anthropic API (DISABLED)
  anthropic:
    enabled: false
    path: "/anthropic"

# Client adapter configuration
client_adapters:
  default_adapter: "standard"  # Pure OpenAI standard compliance
