# LLM Link Configuration - Pure OpenAI Protocol
#
# This configuration exposes ONLY OpenAI-compatible API endpoints
# Perfect for tools that expect standard OpenAI API (like Codex CLI, ChatGPT clients, etc.)

# Server configuration
server:
  host: "0.0.0.0"
  port: 8080                     # Standard HTTP port for OpenAI API
  log_level: "info"

# LLM backend configuration
llm_backend:
  type: "Zhipu"
  base_url: "https://open.bigmodel.cn/api/paas/v4"
  api_key: "${ZHIPU_API_KEY}"
  model: "glm-4-flash"

# API endpoint configurations - ONLY OpenAI API
apis:
  # OpenAI-compatible API (ENABLED)
  openai:
    enabled: true
    path: "/v1"                  # Standard OpenAI path: /v1/chat/completions, /v1/models
    api_key_header: "Authorization"
    api_key: "${LLM_LINK_API_KEY}"

  # Ollama API (DISABLED)
  ollama:
    enabled: false
    path: "/ollama"
    api_key_header: null
    api_key: null

  # Anthropic API (DISABLED)
  anthropic:
    enabled: false
    path: "/anthropic"

# Client adapter configuration
client_adapters:
  default_adapter: "openai"      # Force OpenAI adapter for all requests
  
  # Disable client-specific adaptations
  zed:
    enabled: false
    force_images_field: false
    preferred_format: "json"
