# LLM Link Configuration - Codex CLI with Environment Variables
#
# This configuration uses environment variables for secure API token management
# Set both ZHIPU_API_KEY and LLM_LINK_API_KEY environment variables before starting

# Server configuration
server:
  host: "0.0.0.0"
  port: 11434
  log_level: "info"

# LLM backend configuration
llm_backend:
  type: "Zhipu"
  base_url: "https://open.bigmodel.cn/api/paas/v4"
  api_key: "${ZHIPU_API_KEY}"
  model: "glm-4-flash"

# API endpoint configurations
apis:
  # OpenAI-compatible API with Bearer token authentication (PRIMARY for Codex)
  openai:
    enabled: true
    path: "/v1"
    api_key_header: "Authorization"
    api_key: "${LLM_LINK_API_KEY}"

  # Ollama-compatible API (SECONDARY for other tools)
  ollama:
    enabled: true
    path: "/ollama"
    api_key_header: null
    api_key: null

  # Anthropic-compatible API (disabled)
  anthropic:
    enabled: false
    path: "/anthropic"

# Client adapter configuration
client_adapters:
  default_adapter: "standard"

  zed:
    enabled: true
    force_images_field: true
    preferred_format: "ndjson"
