# LLM Link Configuration - Codex CLI with Environment Variables
#
# This configuration uses environment variables for secure API token management
# Set LLM_LINK_API_KEY environment variable before starting

# Server configuration
server:
  host: "0.0.0.0"
  port: 11434
  log_level: "info"

# LLM backend configuration
llm_backend:
  type: "Zhipu"
  base_url: "https://open.bigmodel.cn/api/paas/v4"
  api_key: "d2a0da2b02954b1f91a0a4ec16d4521b.GA2Tz9sF9kt4zVd3"
  model: "glm-4-flash"

# API endpoint configurations
apis:
  # OpenAI-compatible API with Bearer token authentication
  openai:
    enabled: true
    path: "/v1"
    # Use environment variable for API token
    api_key_header: "Authorization"
    api_key: "${LLM_LINK_API_KEY}"  # Will be replaced with env var value

  # Ollama-compatible API (no auth)
  ollama:
    enabled: true
    path: "/ollama"
    api_key_header: null
    api_key: null

  # Anthropic-compatible API (disabled)
  anthropic:
    enabled: false
    path: "/anthropic"

# Client adapter configuration
client_adapters:
  default_adapter: "standard"
  
  zed:
    enabled: true
    force_images_field: true
    preferred_format: "ndjson"
