# LLM Link Configuration - Codex CLI Pure OpenAI API
#
# This configuration provides ONLY OpenAI-compatible API for Codex CLI
# Pure OpenAI standard compliance on port 8088

# Server configuration
server:
  host: "0.0.0.0"
  port: 8088
  log_level: "info"

# LLM backend configuration
llm_backend:
  type: "Zhipu"
  base_url: "https://open.bigmodel.cn/api/paas/v4"
  api_key: "${ZHIPU_API_KEY}"
  model: "glm-4-flash"

# API endpoint configurations - PURE OpenAI API ONLY
apis:
  # OpenAI-compatible API (ONLY API enabled)
  openai:
    enabled: true
    path: "/v1"
    api_key_header: "Authorization"
    api_key: "${LLM_LINK_API_KEY}"

  # Ollama API (DISABLED - not needed for Codex)
  ollama:
    enabled: false
    path: "/ollama"
    api_key_header: null
    api_key: null

  # Anthropic API (DISABLED)
  anthropic:
    enabled: false
    path: "/anthropic"

# Client adapter configuration - Pure OpenAI standard
client_adapters:
  default_adapter: "standard"  # Pure OpenAI compliance
  
  # Disable all client-specific adaptations for pure OpenAI compatibility
  zed:
    enabled: false
    force_images_field: false
    preferred_format: "json"
