# Model configurations for different LLM providers
# This file contains popular and commonly used models for each provider
# Update this file to add/remove models without changing code

openai:
  models:
    - id: "gpt-4"
      name: "GPT-4"
      description: "Most capable GPT-4 model"
    - id: "gpt-4-turbo"
      name: "GPT-4 Turbo"
      description: "Latest GPT-4 Turbo model"
    - id: "gpt-4o"
      name: "GPT-4o"
      description: "GPT-4 Omni model"
    - id: "gpt-4o-mini"
      name: "GPT-4o Mini"
      description: "Smaller, faster GPT-4o model"
    - id: "gpt-3.5-turbo"
      name: "GPT-3.5 Turbo"
      description: "Fast and efficient model"
    - id: "gpt-3.5-turbo-16k"
      name: "GPT-3.5 Turbo 16K"
      description: "Extended context version"

anthropic:
  models:
    - id: "claude-3-5-sonnet-20241022"
      name: "Claude 3.5 Sonnet"
      description: "Latest Claude 3.5 Sonnet model"
    - id: "claude-3-5-haiku-20241022"
      name: "Claude 3.5 Haiku"
      description: "Fast and efficient Claude model"
    - id: "claude-3-opus-20240229"
      name: "Claude 3 Opus"
      description: "Most capable Claude 3 model"
    - id: "claude-3-sonnet-20240229"
      name: "Claude 3 Sonnet"
      description: "Balanced Claude 3 model"
    - id: "claude-3-haiku-20240307"
      name: "Claude 3 Haiku"
      description: "Fastest Claude 3 model"

zhipu:
  models:
    - id: "glm-4-flash"
      name: "GLM-4 Flash"
      description: "Fast model for quick tasks"
    - id: "glm-4-plus"
      name: "GLM-4 Plus"
      description: "Enhanced model for complex tasks"
    - id: "glm-4"
      name: "GLM-4"
      description: "Standard model"
    - id: "glm-4-air"
      name: "GLM-4 Air"
      description: "Lightweight model"
    - id: "glm-4-long"
      name: "GLM-4 Long"
      description: "Long context model"
    - id: "glm-4-0520"
      name: "GLM-4 0520"
      description: "GLM-4 May 2024 version"

ollama:
  models:
    - id: "llama3.2"
      name: "Llama 3.2"
      description: "Latest Llama model"
    - id: "llama3.1"
      name: "Llama 3.1"
      description: "Llama 3.1 model"
    - id: "llama3"
      name: "Llama 3"
      description: "Llama 3 model"
    - id: "llama2"
      name: "Llama 2"
      description: "Llama 2 model"
    - id: "codellama"
      name: "Code Llama"
      description: "Code-specialized Llama model"
    - id: "mistral"
      name: "Mistral"
      description: "Mistral 7B model"
    - id: "mixtral"
      name: "Mixtral"
      description: "Mixtral 8x7B model"
    - id: "qwen2.5"
      name: "Qwen 2.5"
      description: "Qwen 2.5 model"
    - id: "deepseek-coder"
      name: "DeepSeek Coder"
      description: "Code-specialized model"
    - id: "phi3"
      name: "Phi-3"
      description: "Microsoft Phi-3 model"

aliyun:
  models:
    - id: "qwen-turbo"
      name: "Qwen Turbo"
      description: "Fast Qwen model"
    - id: "qwen-plus"
      name: "Qwen Plus"
      description: "Enhanced Qwen model"
    - id: "qwen-max"
      name: "Qwen Max"
      description: "Most capable Qwen model"
    - id: "qwen-max-longcontext"
      name: "Qwen Max Long Context"
      description: "Long context Qwen model"
    - id: "qwen2.5-72b-instruct"
      name: "Qwen 2.5 72B"
      description: "Large Qwen 2.5 model"
    - id: "qwen2.5-32b-instruct"
      name: "Qwen 2.5 32B"
      description: "Medium Qwen 2.5 model"
    - id: "qwen2.5-14b-instruct"
      name: "Qwen 2.5 14B"
      description: "Smaller Qwen 2.5 model"
